fiber_server:
  HttpPort: ":8081"
  Mode: "Development"
  BodyLimitInKb: 102400

grpc_connection:
  EmployeeService: "127.0.0.1:50051"

postgres:
  ConnectionString: "postgres://kaido1712:kaido1712@127.0.0.1:5433/asset_management?sslmode=disable&TimeZone=Asia/Ho_Chi_Minh"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: true
  Encoding: "json"
  Level: "info"
  SugarType: true


rabbitmq:
  URI: "amqps://asset_server:kaido1712@127.0.0.1:5672/asset_management"
  LabelTaskQueue: "label_task_queue"
  CompletedLabelTaskQueue: "completed_label_task_queue"

minio:
  Endpoint: "127.0.0.1:9000"
  AccessKeyID: "GmrlC2mP8bGnpvYZjnym"
  SecretAccessKey: "spYleTko6ZOm5F7AuWX0gqEEtnnzDWK38EWVmI27"
  Bucket: "asset-management"

redis:
  Addr: "redis-12661.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com:12661"
  Username: "default"
  Password: "OOH5lf9owZA07XtHBtJsU8JL8se9yief"
  DB: 0

auth: 
  JwtAccessTokenKeyString: "do_an_tot_nghiep" 
  JwtAccessTokenExpireTimeInMinutes: 120